version: '3.9'

services:
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=server=${HOST};port=${PORT};user=${USER};password=${DBKEY};database=${DB}
