# This is a generated file. Not intended for manual editing.
services:
  webapp:
    build:
      context: "C:\\dev\\educode-backend"
      dockerfile: "WebApp/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/WebApp.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net9.0/WebApp.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapp:dev"
    ports: []
    volumes:
    - "C:\\dev\\educode-backend\\WebApp:/app:rw"
    - "C:\\dev\\educode-backend:/src:rw"
    - "C:\\Users\\alder\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
